### ISSUE TITLE
Modifications to error.rs is not full.

### ISSUE THREAD

**Issue by ghost** [paul-schaaf/blog#8]
The tutorial seems to be missing 3 error enum types: NotRentExempt, ExpectedAmountMismatch and AmountOverflow when comparing error.rs we get in the tutorial to the error.rs in source code.

**Comment by paul-schaaf** [comment]
hi @Voodlaz If you do a ctrl/cmd + F on the blog post for these errors, you'll see that after each code block where they first appear, I tell you to implement these errors yourself! If you know how to implement the first error, you know how to implement the rest of them!

**Comment by ghost** [comment]
@paul-schaaf Oh, okay.
